import re
content = open('backend/app/services/ai/base.py', encoding='utf-8').read()
new_base_method = """
    def generate_session_recap(self, answered_data: list[dict]) -> dict:
        raise NotImplementedError("Subclasses must implement generate_session_recap")
"""
content += new_base_method
open('backend/app/services/ai/base.py', 'w', encoding='utf-8').write(content)

content = open('backend/app/services/ai/groq_client.py', encoding='utf-8').read()
new_groq_method = """
    def generate_session_recap(self, answered_data: list[dict]) -> dict:
        import json
        import httpx
        
        prompt_text = f\"\"\"You are an expert evaluator assessing a student's software project defense.
Review the following Q&A session. Summarize the student's overall performance.
Include qualitative observations across project understanding, flow explanation, technical clarity, use of relevant details, and evidence awareness. Summarize strengths and a few practical areas to work on next.
If unanswered questions were skipped, do not imply they were completed.

Session Data:
{json.dumps(answered_data, indent=2)}

Return ONLY a valid JSON object matching this exact schema:
{{
    "recap": "<your detailed summary recap>"
}}
\"\"\"
        headers = {
            "Authorization": f"Bearer {self.api_key.strip()}",
            "Content-Type": "application/json"
        }
        
        client_cm = (
            self.http_client
            if self.http_client is not None
            else httpx.Client(timeout=self.timeout_seconds)
        )
        
        try:
            resp = client_cm.post(
                GROQ_API_URL,
                headers=headers,
                json={
                    "model": self.model_name,
                    "messages": [{"role": "user", "content": prompt_text}],
                    "response_format": {"type": "json_object"}
                }
            )
            resp.raise_for_status()
            data = resp.json()
            raw_text = data["choices"][0]["message"]["content"]
            parsed = json.loads(raw_text)
            return {"recap": parsed.get("recap", "No recap generated.")}
        except Exception as e:
            logger.error(f"Groq error generating session recap: {e}")
            raise
        finally:
            if self.http_client is None:
                client_cm.close()
"""
content += new_groq_method
open('backend/app/services/ai/groq_client.py', 'w', encoding='utf-8').write(content)

# We should also add it to mock_provider.py
content = open('backend/app/services/ai/mock_provider.py', encoding='utf-8').read()
new_mock_method = """
    def generate_session_recap(self, answered_data: list[dict]) -> dict:
        return {"recap": "This is a deterministic fallback recap generated by the mock provider."}
"""
content += new_mock_method
open('backend/app/services/ai/mock_provider.py', 'w', encoding='utf-8').write(content)
