"""Add session_recap

Revision ID: 0c60a8997e7a
Revises: ce4aa160fe22
Create Date: 2026-10-04 21:03:34.102955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c60a8997e7a'
down_revision: Union[str, Sequence[str], None] = 'ce4aa160fe22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defend_sessions', sa.Column('session_recap', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defend_sessions', 'session_recap')
    # ### end Alembic commands ###
