"""create document extractions and project understandings tables

Revision ID: 20a05a1dd259
Revises: 1f5a7e40f7fe
Create Date: 2026-09-17 21:53:44.595608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a05a1dd259'
down_revision: Union[str, Sequence[str], None] = '1f5a7e40f7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_understandings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('target_users', sa.JSON(), nullable=True),
    sa.Column('objectives', sa.JSON(), nullable=True),
    sa.Column('requirements_summary', sa.Text(), nullable=True),
    sa.Column('modules', sa.JSON(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('architecture_overview', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('expected_scale', sa.Text(), nullable=True),
    sa.Column('deployment', sa.Text(), nullable=True),
    sa.Column('team', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('source_artifact_ids', sa.JSON(), nullable=True),
    sa.Column('extracted_sections_count', sa.Integer(), nullable=False),
    sa.Column('total_words_analyzed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_understandings_project_id'), 'project_understandings', ['project_id'], unique=True)
    op.create_index(op.f('ix_project_understandings_status'), 'project_understandings', ['status'], unique=False)
    op.create_table('document_extractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('extractor_name', sa.String(length=100), nullable=False),
    sa.Column('text_storage_path', sa.String(length=500), nullable=True),
    sa.Column('text_preview', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extractions_artifact_id'), 'document_extractions', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_document_extractions_project_id'), 'document_extractions', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_extractions_status'), 'document_extractions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_extractions_status'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_project_id'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_artifact_id'), table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index(op.f('ix_project_understandings_status'), table_name='project_understandings')
    op.drop_index(op.f('ix_project_understandings_project_id'), table_name='project_understandings')
    op.drop_table('project_understandings')
    # ### end Alembic commands ###
