"""Add improvement plan items

Revision ID: 4c0aefadfea9
Revises: 5b2c3d4e5f6a
Create Date: 2026-09-30 21:25:55.803099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0aefadfea9'
down_revision: Union[str, Sequence[str], None] = '5b2c3d4e5f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'finding_id', name='uq_improvement_analysis_finding')
    )
    op.create_index(op.f('ix_improvement_items_analysis_id'), 'improvement_items', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_improvement_items_finding_id'), 'improvement_items', ['finding_id'], unique=False)
    op.create_index(op.f('ix_improvement_items_project_id'), 'improvement_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_improvement_items_status'), 'improvement_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_improvement_items_status'), table_name='improvement_items')
    op.drop_index(op.f('ix_improvement_items_project_id'), table_name='improvement_items')
    op.drop_index(op.f('ix_improvement_items_finding_id'), table_name='improvement_items')
    op.drop_index(op.f('ix_improvement_items_analysis_id'), table_name='improvement_items')
    op.drop_table('improvement_items')
    # ### end Alembic commands ###
