"""create requirements and requirement evidence tables

Revision ID: 7d91c33b40c7
Revises: 20a05a1dd259
Create Date: 2026-09-17 22:45:18.859244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d91c33b40c7'
down_revision: Union[str, Sequence[str], None] = '20a05a1dd259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('conflict_summary', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'content_hash', name='uq_project_requirement_content_hash')
    )
    op.create_index(op.f('ix_requirements_category'), 'requirements', ['category'], unique=False)
    op.create_index(op.f('ix_requirements_content_hash'), 'requirements', ['content_hash'], unique=False)
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirements_requirement_id'), 'requirements', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_requirements_status'), 'requirements', ['status'], unique=False)
    op.create_table('requirement_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_name', sa.String(length=255), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('exact_snippet', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'source_type', 'artifact_id', 'exact_snippet', name='uq_req_evidence_unique_source')
    )
    op.create_index(op.f('ix_requirement_evidence_artifact_id'), 'requirement_evidence', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_requirement_evidence_project_id'), 'requirement_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirement_evidence_requirement_id'), 'requirement_evidence', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_evidence_requirement_id'), table_name='requirement_evidence')
    op.drop_index(op.f('ix_requirement_evidence_project_id'), table_name='requirement_evidence')
    op.drop_index(op.f('ix_requirement_evidence_artifact_id'), table_name='requirement_evidence')
    op.drop_table('requirement_evidence')
    op.drop_index(op.f('ix_requirements_status'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_requirement_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_content_hash'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_category'), table_name='requirements')
    op.drop_table('requirements')
    # ### end Alembic commands ###
