"""add_analysis_run_and_update_improvement_item

Revision ID: 9ad35f8fac55
Revises: 4c0aefadfea9
Create Date: 2026-10-04 14:16:29.323586

"""
from typing import Sequence, Union
import json
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad35f8fac55'
down_revision: Union[str, Sequence[str], None] = '4c0aefadfea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create analysis_runs
    op.create_table('analysis_runs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('project_id', sa.Uuid(), nullable=False),
        sa.Column('snapshot_id', sa.Uuid(), nullable=True),
        sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
        sa.Column('deterministic_status', sa.String(length=50), nullable=False),
        sa.Column('ai_status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_snapshot_id'), 'analysis_runs', ['snapshot_id'], unique=False)

    # Note: Ignored the drop unique on github_repositories generated by alembic, it's irrelevant.

    # 2. Add columns to improvement_items, initially nullable to allow backfill
    with op.batch_alter_table('improvement_items') as batch_op:
        batch_op.add_column(sa.Column('original_run_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('stable_identity', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('latest_verification_run_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('latest_matching_finding_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), nullable=True))

    # 3. Backfill stable_identity and verification_status
    connection = op.get_bind()
    
    # We need to fetch findings to compute stable_identity
    findings = connection.execute(sa.text("SELECT id, technical_details FROM findings")).fetchall()
    finding_map = {}
    for f in findings:
        f_id = f[0]
        try:
            tech_details = json.loads(f[1]) if isinstance(f[1], str) else f[1]
            rule_code = tech_details.get("rule_code", "UNKNOWN")
            entity_id = tech_details.get("requirement_id") or tech_details.get("file_path") or "repo"
            finding_map[f_id] = f"{rule_code}:{entity_id}"
        except Exception:
            finding_map[f_id] = "UNKNOWN:unknown"

    # Fetch items and compute stable identity
    items = connection.execute(sa.text("SELECT id, project_id, analysis_id, finding_id FROM improvement_items")).fetchall()
    
    
    # We want to deduplicate items by (project_id, stable_identity)
    # If a duplicate exists, keep it but append a UUID so it doesn't violate the unique constraint.
    seen = set()

    for item in items:
        i_id, p_id, a_id, f_id = item[0], item[1], item[2], item[3]
        f_id_uuid = uuid.UUID(f_id.hex) if hasattr(f_id, 'hex') else f_id
        if isinstance(f_id_uuid, bytes):
            f_id_uuid = str(uuid.UUID(bytes=f_id_uuid))
        elif not isinstance(f_id_uuid, str):
            f_id_uuid = str(f_id_uuid)

        stable_id = finding_map.get(f_id_uuid, "UNKNOWN:unknown")
        
        # Determine if we keep it
        key = (p_id, stable_id)
        if key in seen:
            stable_id = f"{stable_id}:dup:{uuid.uuid4().hex[:8]}"
            ver_status = "needs_review"
        else:
            seen.add(key)
            ver_status = "unverified"
            if stable_id == "UNKNOWN:unknown":
                ver_status = "needs_review"
                
        connection.execute(
            sa.text("UPDATE improvement_items SET stable_identity = :sid, verification_status = :vstatus WHERE id = :iid"),
            {"sid": stable_id, "vstatus": ver_status, "iid": i_id}
        )

# 4. Finalize columns and constraints using batch_alter_table for SQLite compatibility
    with op.batch_alter_table('improvement_items') as batch_op:
        # We assume analysis_id and finding_id are named FKs in SQLite, but typically they might be unnamed.
        # Alembic might not drop them cleanly in sqlite without batch mode rebuilding the table.
        # batch_alter_table will recreate the table with the new constraints.
        
        batch_op.alter_column('stable_identity', nullable=False)
        batch_op.alter_column('verification_status', nullable=False, server_default="unverified")
        batch_op.alter_column('analysis_id', nullable=True)
        batch_op.alter_column('finding_id', nullable=True)

        batch_op.drop_constraint('uq_improvement_analysis_finding', type_='unique')
        batch_op.create_unique_constraint('uq_project_stable_identity', ['project_id', 'stable_identity'])

        batch_op.create_foreign_key('fk_ii_orig_run', 'analysis_runs', ['original_run_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_ii_latest_run', 'analysis_runs', ['latest_verification_run_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_ii_latest_finding', 'findings', ['latest_matching_finding_id'], ['id'], ondelete='SET NULL')

        batch_op.create_index(batch_op.f('ix_improvement_items_latest_verification_run_id'), ['latest_verification_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_items_original_run_id'), ['original_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_items_stable_identity'), ['stable_identity'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_items_verification_status'), ['verification_status'], unique=False)



def downgrade() -> None:
    # Reverse of 9ad35f8fac55
    connection = op.get_bind()
    null_count = connection.execute(sa.text("SELECT COUNT(*) FROM improvement_items WHERE analysis_id IS NULL OR finding_id IS NULL")).scalar()
    if null_count > 0:
        raise ValueError(
            f"Cannot safely downgrade: {null_count} improvement items have NULL analysis_id or finding_id. "
            "These items were created by the new feature and cannot be mapped to the old analysis-scoped schema. "
            "Downgrade aborted to prevent data loss or constraint corruption."
        )

    with op.batch_alter_table('improvement_items') as batch_op:
        batch_op.drop_constraint('uq_project_stable_identity', type_='unique')
        batch_op.drop_constraint('fk_ii_orig_run', type_='foreignkey')
        batch_op.drop_constraint('fk_ii_latest_run', type_='foreignkey')
        batch_op.drop_constraint('fk_ii_latest_finding', type_='foreignkey')
        
        batch_op.drop_index(batch_op.f('ix_improvement_items_latest_verification_run_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_items_original_run_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_items_stable_identity'))
        batch_op.drop_index(batch_op.f('ix_improvement_items_verification_status'))

        batch_op.drop_column('verification_status')
        batch_op.drop_column('latest_matching_finding_id')
        batch_op.drop_column('latest_verification_run_id')
        batch_op.drop_column('stable_identity')
        batch_op.drop_column('original_run_id')
        
        # The column finding_id and analysis_id will be handled by the fact that they were originally NOT NULL
        # However, SQLite batch alter table requires us to just alter them.
        batch_op.alter_column('analysis_id', nullable=False)
        batch_op.alter_column('finding_id', nullable=False)
        
        # recreate the old unique constraint
        batch_op.create_unique_constraint('uq_improvement_analysis_finding', ['analysis_id', 'finding_id'])

    op.drop_index(op.f('ix_analysis_runs_snapshot_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
